# Análise de dados "Boston" em R
## Introdução
O Boston Housing Dataset é um conjunto de dados amplamente utilizado, principalmente por estar disponível gratuitamente, na análise estatística e aprendizado de máquina. O conjunto de dados contém informções sobre características de casas na cidade de Boston, mostra o número de quartos, proximidade de centros de empregos, número de quartos, etc.. O objetivo dos dados é prever o valor médio das casas ocupadas pelos proprietários.

## Objetivo
O objetivo deste trabalho é desenvolver e avaliar os modelos preditivos capazes de estimar o valor médio (medv) das casas no Boston Housing Dataset.

## Metodologia
Para conseguirmos estimar o medv utilizaremos diversas abordagens aprendidas na disciplina, os métodos utilizados serão: regressão linear, árvore de decisão e modelo de random forest. Finalmente, avaliaremos os modelos utilizando a validação cruzada e métricas de desempenho (RMSE, R²).

## Desenvolvimento
### Carregar os dados e analisar
Verificou-ses que não há dados nulos, verificamo o formato dos dados e assim poderemos continuar com a análise dos dados.

In [ ]:
library(MASS)
data("Boston")
head(Boston)
str(Boston)
sum(is.na(Boston))

  crim    zn indus chas nox   rm    age  dis    rad tax ptratio black  lstat
1 0.00632 18 2.31  0    0.538 6.575 65.2 4.0900 1   296 15.3    396.90 4.98
2 0.02731  0 7.07  0    0.469 6.421 78.9 4.9671 2   242 17.8    396.90 9.14
3 0.02729  0 7.07  0    0.469 7.185 61.1 4.9671 2   242 17.8    392.83 4.03
4 0.03237  0 2.18  0    0.458 6.998 45.8 6.0622 3   222 18.7    394.63 2.94
5 0.06905  0 2.18  0    0.458 7.147 54.2 6.0622 3   222 18.7    396.90 5.33
6 0.02985  0 2.18  0    0.458 6.430 58.7 6.0622 3   222 18.7    394.12 5.21
  medv
1 24.0
2 21.6
3 34.7
4 33.4
5 36.2
6 28.7

'data.frame':	506 obs. of  14 variables:
 $ crim   : num  0.00632 0.02731 0.02729 0.03237 0.06905 ...
 $ zn     : num  18 0 0 0 0 0 12.5 12.5 12.5 12.5 ...
 $ indus  : num  2.31 7.07 7.07 2.18 2.18 2.18 7.87 7.87 7.87 7.87 ...
 $ chas   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ nox    : num  0.538 0.469 0.469 0.458 0.458 0.458 0.524 0.524 0.524 0.524 ...
 $ rm     : num  6.58 6.42 7.18 7 7.15 ...
 $ age    : num  65.2 78.9 61.1 45.8 54.2 58.7 66.6 96.1 100 85.9 ...
 $ dis    : num  4.09 4.97 4.97 6.06 6.06 ...
 $ rad    : int  1 2 2 3 3 3 5 5 5 5 ...
 $ tax    : num  296 242 242 222 222 222 311 311 311 311 ...
 $ ptratio: num  15.3 17.8 17.8 18.7 18.7 18.7 15.2 15.2 15.2 15.2 ...
 $ black  : num  397 397 393 395 397 ...
 $ lstat  : num  4.98 9.14 4.03 2.94 5.33 ...
 $ medv   : num  24 21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 ...

[1] 0

### Instalação de pacotes
Optou-se pelo uso dos packages caret e randomForest, o caret para avaliação e comparação de modelos de aprendizado de máquina, enquanto o randomForest é justamente para termos a implementação otimizada do algoritimo que dá nome ao pacote.

In [ ]:
install.packages("caret")
install.packages("randomForest")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

### Criação dos modelos
Utilizando as bibliotecas definimos então os três modelos, todos definidos segundo a variável train_control.

In [ ]:
library(caret)
#Definição do controle dos modelos
train_control = trainControl(method = "cv",number = 10, savePredictions = "final")

#Regressão linear
model_lm = train(medv ~ ., data = Boston, method = "lm", trControl = train_control)

# Árvore de decisão
model_tree <- train(medv ~ ., data = Boston, method = "rpart", trControl = train_control)

# Modelo de Random Forest
model_rf <- train(medv ~ ., data = Boston, method = "rf", trControl = train_control)

### Comparando os modelos
Finalmente utilizamos a validação Cruzada para comparar os modelos.

In [ ]:
## Visualizar resultados
model_lm$results
model_tree$results
model_rf$results

# Exemplo de erro quadrático médio (RMSE)
rmse_lm <- sqrt(mean((model_lm$pred$obs - model_lm$pred$pred)^2))
rmse_tree <- sqrt(mean((model_tree$pred$obs - model_tree$pred$pred)^2))
rmse_rf <- sqrt(mean((model_rf$pred$obs - model_rf$pred$pred)^2))

# Exemplo de correlação
cor_lm <- cor(model_lm$pred$obs, model_lm$pred$pred)
cor_tree <- cor(model_tree$pred$obs, model_tree$pred$pred)
cor_rf <- cor(model_rf$pred$obs, model_rf$pred$pred)

# Exibir resultados
print(paste("RMSE Linear Model: ", rmse_lm))
print(paste("RMSE Decision Tree: ", rmse_tree))
print(paste("RMSE Random Forest: ", rmse_rf))

print(paste("Correlation Linear Model: ", cor_lm))
print(paste("Correlation Decision Tree: ", cor_tree))
print(paste("Correlation Random Forest: ", cor_rf))

  intercept RMSE     Rsquared  MAE      RMSESD    RsquaredSD MAESD
1 TRUE      4.794289 0.7261461 3.375577 0.8111512 0.08455267 0.4134839

  cp         RMSE     Rsquared  MAE      RMSESD    RsquaredSD MAESD
1 0.07165784 5.942553 0.5774787 4.190080 0.9609964 0.13889134 0.5292271
2 0.17117244 6.858337 0.4470506 4.990981 0.8930959 0.13280470 0.5680552
3 0.45274420 8.629319 0.3005004 6.275556 1.0463108 0.07617109 0.7877669

  mtry RMSE     Rsquared  MAE      RMSESD    RsquaredSD MAESD
1  2   3.436344 0.8792406 2.314797 0.7189909 0.04823816 0.2528071
2  7   3.044842 0.8922016 2.109477 0.6975811 0.05087953 0.3853833
3 13   3.193974 0.8759073 2.203966 0.9452304 0.08145265 0.4950270

[1] "RMSE Linear Model:  4.86093554959021"
[1] "RMSE Decision Tree:  6.00540230547699"
[1] "RMSE Random Forest:  3.11063236368565"
[1] "Correlation Linear Model:  0.848721738578612"
[1] "Correlation Decision Tree:  0.757549827447969"
[1] "Correlation Random Forest:  0.942360296180247"

### Análise dos resultados
Os três modelos foram gerados e posteriormente avaliados através da validação cruzada e métricas de desempenho como o RMSE (erro quadrático médio), o R².